apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
    - image: nginx
      name: s3-test-container
      securityContext:
        privileged: true
      volumeMounts:
        - name: mnt-goofys
          mountPath: /var/s3:shared
          subPath: helge
      livenessProbe:
        exec:
          command: ["ls", "/var/s3"]
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
  volumes:
    - name: mnt-goofys
      hostPath:
        path: /mnt/data-goofys