apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cate-webui.fullname" . }}
  labels:
    {{- include "cate-webui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webui.replicaCount }}
  selector:
    matchLabels:
      {{- include "cate-webui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cate-webui.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.webui.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "cate-webui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.webui.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.webui.securityContext | nindent 12 }}
          image: "{{ .Values.webui.image.repository }}:{{ .Values.webui.image.version }}"
          imagePullPolicy: {{ .Values.webui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.webui.resources | nindent 12 }}
      {{- with .Values.webui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.webui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.webui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
