apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webui.name }}
  labels:
    {{- include "cate-webui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webui.service.type }}
  ports:
    - port: {{ .Values.webui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cate-webui.selectorLabels" . | nindent 4 }}


---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.xcubehub.name }}
  labels:
  {{- include "xcubehub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.xcubehub.service.type }}
  ports:
    - port: {{ .Values.xcubehub.service.port }}
      targetPort: {{ .Values.xcubehub.port }}
      protocol: TCP
      name: http-{{ .Values.xcubehub.name }}
  selector:
  {{- include "xcubehub.selectorLabels" . | nindent 4 }}
