{{- if .Values.pvWorkspace.nfs -}}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace-pv
  labels:
    app: cate-workspace-prod
{{/*  annotations:*/}}
{{/*    pv.beta.kubernetes.io/gid: "100"*/}}
{{/*    pv.beta.kubernetes.io/uid: "1000"*/}}
spec:
  storageClassName: nfs
  capacity:
    storage: {{ .Values.pvWorkspace.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.pvWorkspace.mountPath }}
    server: {{ .Values.pvWorkspace.nfsServer }}

{{ else }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace-pv
  labels:
    app: cate-workspace-dev
{{/*  annotations:*/}}
{{/*    pv.beta.kubernetes.io/gid: "100"*/}}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.pvWorkspace.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.pvWorkspace.mountPath }}

{{ end }}
