{{- if .Values.pvWorkspace.nfs -}}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcWorkspace.name }}
spec:
  storageClassName: {{ .Values.pvWorkspace.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvWorkspace.capacity }}

{{ else }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcWorkspace.name }}
spec:
  storageClassName: {{ .Values.pvWorkspace.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvWorkspace.capacity }}
  accessModes:
    - ReadWriteOnce

{{ end }}
