{{- if .Values.xcubehub.serviceAccount.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.xcubehub.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.xcubehub.name }}
    namespace: {{ .Values.xcubehub.namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

{{- end -}}