{{- if .Values.xcubehub.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.xcubehub.name }}
  namespace: {{ .Values.xcubehub.namespace }}
  labels:
    {{- include "xcubehub.labels" . | nindent 4 }}
  {{- with .Values.xcubehub.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
