apiVersion: v1
kind: ConfigMap
metadata:
  name: cate-stores
data:
  stores.yaml: |-
{{ .Files.Get "cfg/stores.yaml" | indent 4 }}
  stores-schema.yaml: |-
{{ .Files.Get "cfg/stores-schema.yaml" | indent 4 }}
