{{ if .Values.daemonS3.create }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: goofys-provider
  name: goofys-provider
spec:
  selector:
    matchLabels:
      app: goofys-provider
  template:
    metadata:
      labels:
        app: goofys-provider
    spec:
      containers:
        - name: goofys
          image: {{ .Values.daemonS3.repository }}:{{ .Values.daemonS3.tag }}
          command:
            - "/usr/local/bin/goofys"
            {{ range .Values.daemonS3.goofys.mountOptions }}
            - "{{ . }}"
            {{ end }}
            - "--uid"
            - {{ .Values.daemonS3.fs.uid }}
            - "--gid"
            - {{ .Values.daemonS3.fs.gid }}
            - "-f"
            - "--region"
            - {{ .Values.daemonS3.bucket.region }}
            - {{ .Values.daemonS3.bucket.name }}
            - "/var/s3"
          env:
            {{- range .Values.daemonS3.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","umount -f /var/s3"]
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - name: devfuse
              mountPath: /dev/fuse
            - name: mnt-goofys
              mountPath: /var/s3:shared
      volumes:
        - name: devfuse
          hostPath:
            path: /dev/fuse
        - name: mnt-goofys
          hostPath:
            path: /var/s3
{{ end }}